# Generated by Django 4.2.7 on 2023-12-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email_id",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("ordered", "Ordered"), ("shipped", "Shipped")],
                default="ordered",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="order",
            table="Order",
        ),
        migrations.AlterModelTable(
            name="orderitems",
            table="OrderItems",
        ),
    ]
