# Generated by Django 4.2.7 on 2023-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("products", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="tags.tags"),
        ),
    ]
